server:
  port: 8080

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.auth0.sash: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: <your-client-id>
            client-secret: <your-client-secret>
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://<your-domain>/
